### ISSUE TITLE
URL Schemes in Logseq blocks will be broken after converting to html 

### ISSUE THREAD

**Issue by why8023** [logseq/mldoc#123]
This original contents in Logseq, which contains the MarginNote URL Schemes:
<img width="526" alt="image" src="https://user-images.githubusercontent.com/22267652/172756866-3f13642f-faf0-41ee-85a5-99c8c1bf30ea.png">
After I select these blocks and copy them as HTML, they will be:
<img width="607" alt="image" src="https://user-images.githubusercontent.com/22267652/172757190-30ce9063-aef9-4c63-963b-265f143bee2c.png">
there are both missing two slash.

**Comment by stdword** [comment]
@cnrpman Issue can be closed: Logseq 0.9.1 and Mldoc 1.5.3 parses url correctly:

```
% echo 'marginnote3app://note/8B11CF4A-DE3C-4A71-84G8-ODF5EE2EBO4C' | npx mldoc convert -f ast
...
Reading data from stdin...
Parsing file...
Converting to ast
Writing data to stdout...
[
    [
        "Link",
        {
            "url": [
                "Complex",
                {
                    "protocol": "marginnote3app",
                    "link": "note/8B11CF4A-DE3C-4A71-84G8-ODF5EE2EBO4C"
                }
            ],
            "label": [
                [
                    "Plain",
                    "marginnote3app://note/8B11CF4A-DE3C-4A71-84G8-ODF5EE2EBO4C"
                ]
            ],
            "full_text": "marginnote3app://note/8B11CF4A-DE3C-4A71-84G8-ODF5EE2EBO4C",
            "metadata": ""
        }
    ],
    [
        "Break_Line"
    ]
]

DONE!
```
