### ISSUE TITLE
markdown lists are rendered as headings

### ISSUE THREAD

**Issue by bensu** [logseq/mldoc#74]
When calling `Mldoc.exporttoHtml` on the following string

```
- first level
  - second level
```

with this config

```
{"toc":false,"heading_number":false,"keep_line_break":true,"format":"Markdown","heading_to_list":true}
```

the output is:

```
<!-- directives: [] -->
<div id="content">
  <h1 id="first_level">first level</h1>
  <h2 id="second_level">second level</h2>
</div>
```

The output is the same whether I pass `heading_to_list` as `true` or `false`.

I would've expected something using `<ul>` and `<li>` like the following instead:

```
<div id="content">
  <ul>
    <li id="first_level">first level</li>
    <ul>
      <li id="second_level">second level</li>
    </ul>
  </ul>
</div>
```

**Comment by RCmerci** [comment]
Yes, `- text` is treated as a heading in logseq, and `+ text`, `* text` are treated as list items. 
Maybe we should add an option to export it as `<li>` item when `Mldoc.exporttoHtml` later.

**Comment by bensu** [comment]
Thank you for the clarification! I solved this problem in this PR by using `+`:

https://github.com/logseq/logseq/pull/2367
