### ISSUE TITLE
bug: single right bracket in org link label

### ISSUE THREAD

**Issue by PoiScript** [logseq/mldoc#94]
Single right bracket in label is not rendering properly:

<img width="547" alt="Screen Shot 2021-08-27 at 1 13 53 PM" src="https://user-images.githubusercontent.com/17513314/131075367-8ecc96fe-d5c2-4529-a53b-2c54e2e94d42.png">

It happens because the parser is now taking every character until it reaches `]` and checks if the remaining part starts with `]]`:

https://github.com/logseq/mldoc/blob/c0b5a837798d7e757b3f4eba162ba33999066fa2/lib/syntax/inline.ml#L627

I think the correct way should be taking every character until it reaches `]]`, something likes `let label_part = take_until "]]"`.

Finally, thank you for brilliant job! Logseq is really an awesome tool.

**Comment by RCmerci** [comment]
hi @PoiScript , thanks for reporting! Just sent a fix PR
